### ISSUE TITLE
AJAX errors

### ISSUE THREAD

**Issue by noloco** [openrestaurant/support#1]
Hello,

I have been trying to test out this build, but I keep getting AJAX errors, both on install of the demo content, and also when trying to add menu items / Variants.

Any idea what could be causing them?

<img width="1206" alt="screen shot 2015-10-23 at 10 54 22 am" src="https://cloud.githubusercontent.com/assets/3975652/10698355/354761a0-7976-11e5-9e6f-af6812f4851f.png">
<img width="870" alt="screen shot 2015-10-23 at 10 35 12 am" src="https://cloud.githubusercontent.com/assets/3975652/10698387/5e374670-7976-11e5-9bf5-3f79d0522a77.png">

**Comment by feldmarv** [comment]
I do have exactly the same problem. The system throws this AJAX error while:
- Step 7 of 10 SQLSTATE[42S22]: Column not found: 1054 Unknown column 'group_name' in 'field list'

After this message its not possible to enable/disable any module.

**Comment by arshad** [comment]
The first error on install is a max_execution_time error. Can you increase the max_execution_time on the server and try again?

Looking into the second AJAX error.

**Comment by zku7** [comment]
Migrate module is the problem....downgrade.

**Comment by Matilda2506** [comment]
I also have an AJAX error in step 7.  I increase max_execution_time = 2400. The error still occurs. How to deal with it?

**Comment by arshad** [comment]
Can you try running the install in standard mode (instead of quick)?

**Comment by Matilda2506** [comment]
I install quick

**Comment by arshad** [comment]
@Matilda2506 did the standard mode work?

**Comment by Matilda2506** [comment]
No.

**Comment by Matilda2506** [comment]
Finish of install STANDART without "Install demo content"


Additional uncaught exception thrown while handling exception.
Original

PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away: DELETE FROM {semaphore} WHERE (name = :db_condition_placeholder_0) AND (value = :db_condition_placeholder_1) ; Array ( [:db_condition_placeholder_0] =&gt; menu_rebuild [:db_condition_placeholder_1] =&gt; 1778928418563b327bb3ad88.07571010 ) in lock_release() (line 254 of F:\XAMPP\htdocs\restaurant\includes\lock.inc).
Additional

PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away: SELECT expire, value FROM {semaphore} WHERE name = :name; Array ( [:name] =&gt; theme_registry:runtime:sizzle:cache ) in lock_may_be_available() (line 167 of F:\XAMPP\htdocs\restaurant\includes\lock.inc).
Uncaught exception thrown in shutdown function.

PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away: DELETE FROM {semaphore} WHERE (value = :db_condition_placeholder_0) ; Array ( [:db_condition_placeholder_0] =&gt; 1778928418563b327bb3ad88.07571010 ) in lock_release_all() (line 269 of F:\XAMPP\htdocs\restaurant\includes\lock.inc).

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in F:\XAMPP\htdocs\restaurant\includes\database\database.inc:2171 Stack trace: #0 F:\XAMPP\htdocs\restaurant\includes\database\database.inc(2171): PDOStatement->execute(Array) #1 F:\XAMPP\htdocs\restaurant\includes\database\database.inc(683): DatabaseStatementBase->execute(Array, Array) #2 F:\XAMPP\htdocs\restaurant\includes\database\database.inc(2350): DatabaseConnection->query('SELECT expire, ...', Array, Array) #3 F:\XAMPP\htdocs\restaurant\includes\lock.inc(167): db_query('SELECT expire, ...', Array) #4 F:\XAMPP\htdocs\restaurant\includes\lock.inc(146): lock_may_be_available('schema:runtime:...') #5 F:\XAMPP\htdocs\restaurant\includes\bootstrap.inc(433): lock_acquire('schema:runtime:...') #6 F:\XAMPP\htdocs\restaurant\includes\bootstrap.inc(455): DrupalCacheArray->set(Array) #7 [internal function]: DrupalCacheArray->__destruct() #8 {main} thrown in F:\XAMPP\htdocs\restaurant\includes\database\database.inc on line 2171
Uncaught exception thrown in session handler.

PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away: SELECT 1 AS expression FROM {sessions} sessions WHERE ( (sid = :db_condition_placeholder_0) AND (ssid = :db_condition_placeholder_1) ); Array ( [:db_condition_placeholder_0] =&gt; tZxi9TOr-jWm9qtyCvbQ5JyrRndsYiHXMVC3XPcYqXk [:db_condition_placeholder_1] =&gt; ) in _drupal_session_write() (line 209 of F:\XAMPP\htdocs\restaurant\includes\session.inc).

**Comment by zku7** [comment]
before installing, replace module migrate to version 2.5

**Comment by arshad** [comment]
Does downgrading migrate to 2.5 fix all the installation errors?

**Comment by zku7** [comment]
Yes for me. your test

**Comment by Matilda2506** [comment]
I changed the module migrate to version 2.5. and at me everything turned out! 
Thank you, zku7!

**Comment by cotelin** [comment]
Matilda2506: 
I had the same MYSQL errors, the problem is with MySql max_allowed_packet  = 16M in my case. I've set it to 256M and it worked. I'm using MAMP on OS 10.11. More details here https://www.drupal.org/node/1014172

**Comment by dwisusanto** [comment]
i have downgraded migrate to 2.5 and using standard profile. The installation is working properly.

**Comment by cukal** [comment]
I was stuck at the same issue :( I'm on MAMP 3.5 & OS 10.11 
Replacing migrate with migrate 2.5 in ~modules/contrib/ returned this error: 
*Cannot redeclare node_type_set_defaults() (previously declared in /Applications/MAMP/htdocs/modules/node/node.module:806) in /Applications/MAMP/htdocs/profiles/restaurant/modules/contrib/migrate/includes/d7.inc on line 12*
What's the correct procedure to downgrade migrate module and get rc2 to fully install demo content?

**Comment by arshad** [comment]
@cukal We're looking into it. You might get some help in the migrate issue queue as well: https://www.drupal.org/project/issues/migrate?categories=All

We're tagging a new release for Open Restaurant this week with this fix as well.

**Comment by cukal** [comment]
@arshad , thanks for you reply. I checked out the current git repository and did a build from there and it installs the demo content without any error which is all I need for now :D Many Thanks!

**Comment by paskainos** [comment]
For what it's worth at this point; I experiened a variety of AJAX / PHP Fatal error / PDOException errors with several attempts at both quick and standard installs, including on Hostgator VPS, Pantheon, and SimplyTest.me. Not to mention, demo content installation was inconsistent (i.e. varying from some to none) across all installs. Downgrading Migrate to version 2.5 eliminated all errors and anomalies on subsequent install.

**Comment by nepaliboy** [comment]
I am a new to drupal, can someone help me how to downgrade migrate ?

**Comment by nepaliboy** [comment]
Also @cukal can you please list the process to download the git repository and build it ? Thanks in advance.

**Comment by arshad** [comment]
@nepaliboy Can you open an issue on drupal.org please? We moved support there. Here's the link: https://www.drupal.org/project/issues/restaurant
