### ISSUE TITLE
Schema.org integration

### ISSUE THREAD

**Issue by tr3vr** [openrestaurant/support#10]
Do you think including RDF features and Schema.org mappings could enhance search results, for e.g. Google Rich-Snippets

**Comment by arshad** [comment]
You can enable the RDF module. We do not enable it by default.

For Schema.org, we're looking into https://www.drupal.org/project/schemaorg but nothing planned yet.

**Comment by tr3vr** [comment]
Thanks, will try to produce RDF enabled Menus, Locations, etc. and post the results back here.
