### ISSUE TITLE
navbar gets misaligned after the changing the menu items

### ISSUE THREAD

**Issue by tr3vr** [openrestaurant/support#11]
Editing the main navigation menu items results the navbar items being slightly left aligned.

For e.g. http://dev-popadam-draft-2.pantheon.io/

**Comment by arshad** [comment]
Here's a temporary fix fo this:

1. Look for the file sizzle.custom.css: `/profiles/restaurant/themes/sizzle/assets/stylesheets/sizzle.custom.css`.
2. Add the following code to it.

```
ul.navbar-nav {
  margin: 0 auto;
  display: table;
  float: none;
}
```

3. Save. Clear your cache and test.
