### ISSUE TITLE
Changing "fa fa-yelp" to "fa fa-tripadvisor" 

### ISSUE THREAD

**Issue by tr3vr** [openrestaurant/support#9]
Changing fa fa-yelp to fa fa-tripadvisor does not reflect the changes to the footer, I found that fortawesome/font-awesome : dev-4.2.0-wip includes fa-tripadvisor, I think it would be very helpful include this as many restaurants use TripAdvisor.

**Comment by arshad** [comment]
We need to update to the latest Fontawesome. Tripadvisor is in 4.4. We'll send an update soon.

**Comment by tr3vr** [comment]
Super, thanks!
